org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.21.1
neo_version=21.1.219
neo_version_range=[21,)
loader_version_range=[4,)
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

mod_id=tlmtrumpet
mod_name=Maid Trumpet Calls
mod_license=MIT
mod_version=1.0.0-neoforge+mc1.21.1
mod_group_id=com.github.eileen
mod_authors=eileen
